services:
  backend:
    build: ./backend/
    environment:
      - POSTGRES_USER=gowithme
      - POSTGRES_PASSWORD=gwm-pwd-123
      - POSTGRES_DB=gowithme
      - SECRET_KEY=guten_tag
    ports:
      - "8080:8080"
