// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/protobuf/services.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Credentials struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Credentials) Reset() {
	*x = Credentials{}
	mi := &file_api_protobuf_services_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Credentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Credentials) ProtoMessage() {}

func (x *Credentials) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_services_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Credentials.ProtoReflect.Descriptor instead.
func (*Credentials) Descriptor() ([]byte, []int) {
	return file_api_protobuf_services_proto_rawDescGZIP(), []int{0}
}

func (x *Credentials) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *Credentials) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type JWTMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JWTMsg) Reset() {
	*x = JWTMsg{}
	mi := &file_api_protobuf_services_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JWTMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JWTMsg) ProtoMessage() {}

func (x *JWTMsg) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_services_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JWTMsg.ProtoReflect.Descriptor instead.
func (*JWTMsg) Descriptor() ([]byte, []int) {
	return file_api_protobuf_services_proto_rawDescGZIP(), []int{1}
}

func (x *JWTMsg) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ProfileInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Surname       string                 `protobuf:"bytes,3,opt,name=surname,proto3" json:"surname,omitempty"`
	Age           int32                  `protobuf:"varint,4,opt,name=age,proto3" json:"age,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Sex           string                 `protobuf:"bytes,6,opt,name=sex,proto3" json:"sex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileInfo) Reset() {
	*x = ProfileInfo{}
	mi := &file_api_protobuf_services_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileInfo) ProtoMessage() {}

func (x *ProfileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_services_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileInfo.ProtoReflect.Descriptor instead.
func (*ProfileInfo) Descriptor() ([]byte, []int) {
	return file_api_protobuf_services_proto_rawDescGZIP(), []int{2}
}

func (x *ProfileInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProfileInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProfileInfo) GetSurname() string {
	if x != nil {
		return x.Surname
	}
	return ""
}

func (x *ProfileInfo) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *ProfileInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProfileInfo) GetSex() string {
	if x != nil {
		return x.Sex
	}
	return ""
}

type Status struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Details       string                 `protobuf:"bytes,2,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_api_protobuf_services_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_services_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_api_protobuf_services_proto_rawDescGZIP(), []int{3}
}

func (x *Status) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Status) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

var File_api_protobuf_services_proto protoreflect.FileDescriptor

const file_api_protobuf_services_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/protobuf/services.proto\"?\n" +
	"\vCredentials\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\x1e\n" +
	"\x06JWTMsg\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\x91\x01\n" +
	"\vProfileInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\asurname\x18\x03 \x01(\tR\asurname\x12\x10\n" +
	"\x03age\x18\x04 \x01(\x05R\x03age\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x10\n" +
	"\x03sex\x18\x06 \x01(\tR\x03sex\"6\n" +
	"\x06Status\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\adetails\x18\x02 \x01(\tR\adetails2g\n" +
	"\x04Auth\x12!\n" +
	"\bRegister\x12\f.Credentials\x1a\a.Status\x12\x1e\n" +
	"\x05Login\x12\f.Credentials\x1a\a.Status\x12\x1c\n" +
	"\bValidate\x12\a.JWTMsg\x1a\a.StatusB\x0eZ\fapi/protobufb\x06proto3"

var (
	file_api_protobuf_services_proto_rawDescOnce sync.Once
	file_api_protobuf_services_proto_rawDescData []byte
)

func file_api_protobuf_services_proto_rawDescGZIP() []byte {
	file_api_protobuf_services_proto_rawDescOnce.Do(func() {
		file_api_protobuf_services_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_protobuf_services_proto_rawDesc), len(file_api_protobuf_services_proto_rawDesc)))
	})
	return file_api_protobuf_services_proto_rawDescData
}

var file_api_protobuf_services_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_protobuf_services_proto_goTypes = []any{
	(*Credentials)(nil), // 0: Credentials
	(*JWTMsg)(nil),      // 1: JWTMsg
	(*ProfileInfo)(nil), // 2: ProfileInfo
	(*Status)(nil),      // 3: Status
}
var file_api_protobuf_services_proto_depIdxs = []int32{
	0, // 0: Auth.Register:input_type -> Credentials
	0, // 1: Auth.Login:input_type -> Credentials
	1, // 2: Auth.Validate:input_type -> JWTMsg
	3, // 3: Auth.Register:output_type -> Status
	3, // 4: Auth.Login:output_type -> Status
	3, // 5: Auth.Validate:output_type -> Status
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_protobuf_services_proto_init() }
func file_api_protobuf_services_proto_init() {
	if File_api_protobuf_services_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_protobuf_services_proto_rawDesc), len(file_api_protobuf_services_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_protobuf_services_proto_goTypes,
		DependencyIndexes: file_api_protobuf_services_proto_depIdxs,
		MessageInfos:      file_api_protobuf_services_proto_msgTypes,
	}.Build()
	File_api_protobuf_services_proto = out.File
	file_api_protobuf_services_proto_goTypes = nil
	file_api_protobuf_services_proto_depIdxs = nil
}
