name: Deploy to Server

on:
  push:
    branches: [ dev, devops ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASS }} 
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd ~/GoWithMe
            docker compose down
            git pull
            docker compose up -d --build