name: Build & Deploy Web

permissions:
  contents: write

on:
  push:
    branches: [ devops ]
  pull_request:
    branches: [ devops ]

jobs:
  build-and-deploy-web:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: |
          cd frontend
          flutter pub get

      - name: Check formatting
        run: |
          cd frontend
          dart format --set-exit-if-changed .

      - name: Run tests with coverage
        run: |
          cd frontend
          flutter test --coverage

      - name: Install lcov
        run: sudo apt-get update && sudo apt-get install -y lcov

      - name: Generate HTML report
        run: |
          cd frontend
          genhtml coverage/lcov.info --output-directory coverage/html

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: flutter-coverage-report
          path: coverage/html

      - name: Static analysis
        run: flutter analyze --no-fatal-warnings --no-fatal-infos

      - name: Build web
        run: |
          cd frontend
          flutter build web --release --base-href='/GoWithMe/'

      - name: Deploy to GitHub Pages
        uses: bluefireteam/flutter-gh-pages@v9
        with:
          baseHref: '/GoWithMe/'
          workingDir: frontend
          customArgs: --target="lib/main.dart"
